openapi: 3.0.0
info:
  title: Backend API
  description: This is a backend API that allows users to register, login, and generate passwords.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /register:
    post:
      operationId: register
      requestBody:
        content:
          application/json:
             schema:
               $ref: '#/components/schemas/login'
        required: true
      responses:
        201:
          description: User registered successfully
        400:
          description: Invalid request
  /login:
    post:
      operationId: login
      requestBody:
        content:
          application/json:
             schema:
               $ref: '#/components/schemas/login'
        required: true
      responses:
        200:
          description: User logged in successfully
        401:
          description: Invalid username or password
  /ping:
    get:
      operationId: ping
      responses:
        200:
          description: Application is running
  /generate:
    get:
      operationId: generate
      parameters:
      - name: password_size
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: Password generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  password:
                    type: string
        400:
          description: Invalid password size
  /isStrong:
    get:
      operationId: isStrong
      requestBody:
        content:
          application/json:
             schema:
               $ref: ''
          required: true
      responses:
        200:
          description: Password is strong
        400:
          description: Password is not strong
  /save:
    post:
      operationId: save
      parameters:
        - in: body
          name: password
          schema:
            type: object
            properties:
              label:
                type: string
              password:
                type: string
          required: true
      responses:
        200:
          description: Password saved successfully
        400:
          description: Invalid password label or password
  /myPassword:
    get:
      operationId: myPassword
      responses:
        200:
          description: Passwords retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    label:
                      type: string
                    password:
                      type: string
        401:
          description: User not logged in
  /deleteUser:
    delete:
      operationId: deleteUser
      parameters:
        - in: path
          name: id
          type: string
          required: true
      responses:
        200:
          description: User deleted successfully
        401:
          description: User not logged in
        404:
          description: User not found
          
          
          
components:
   schemas:
    login:
      type: object
      properties:
        username:
          type: string
          example: "fifaliana"
        password:
          type: string
          example: "loica123"    